// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmHTyxiU86ZQSCytUQrw5wTylj12gGonc',
    appId: '1:1014629558804:web:a8e7b6630e4d6dbca79501',
    messagingSenderId: '1014629558804',
    projectId: 'finalprojectapp-unltimedia',
    authDomain: 'finalprojectapp-unltimedia.firebaseapp.com',
    storageBucket: 'finalprojectapp-unltimedia.firebasestorage.app',
    measurementId: 'G-3NRQWSH4T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsDQvX92eAmDJV0J62ayvp2gRLhoEXvgU',
    appId: '1:1014629558804:android:6e2123d90db6bc65a79501',
    messagingSenderId: '1014629558804',
    projectId: 'finalprojectapp-unltimedia',
    storageBucket: 'finalprojectapp-unltimedia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe9qmXs7wdQQQJa6FA8NOyNdbZcm1GWzY',
    appId: '1:1014629558804:ios:7c35a0892ac50484a79501',
    messagingSenderId: '1014629558804',
    projectId: 'finalprojectapp-unltimedia',
    storageBucket: 'finalprojectapp-unltimedia.firebasestorage.app',
    iosBundleId: 'com.example.finalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe9qmXs7wdQQQJa6FA8NOyNdbZcm1GWzY',
    appId: '1:1014629558804:ios:7c35a0892ac50484a79501',
    messagingSenderId: '1014629558804',
    projectId: 'finalprojectapp-unltimedia',
    storageBucket: 'finalprojectapp-unltimedia.firebasestorage.app',
    iosBundleId: 'com.example.finalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmHTyxiU86ZQSCytUQrw5wTylj12gGonc',
    appId: '1:1014629558804:web:c66ef47fd4310690a79501',
    messagingSenderId: '1014629558804',
    projectId: 'finalprojectapp-unltimedia',
    authDomain: 'finalprojectapp-unltimedia.firebaseapp.com',
    storageBucket: 'finalprojectapp-unltimedia.firebasestorage.app',
    measurementId: 'G-JCTMF345B6',
  );
}
